// <auto-generated />
using HD_SUPPORT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HD_SUPPORT.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HD_SUPPORT.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("HD_SUPPORT.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriaUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Headset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPatrimonio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InicioEmprestimo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeloMarca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaOperacional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminoEmprestimo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
